platform :ios, "6.0"

pod 'DMLogFormatter', '~> 1.0.0'
pod 'EDColor', '~> 0.2.0'
pod 'CocoaLumberjack', '~> 1.6.2'
pod 'AFNetworking', '~> 1.3.1'
pod 'JMImageCache', '~> 0.4.0'
pod 'SIAlertView', '~> 1.1'